export const PROJECT_GET = "[PROJECT] GET_PROJECT";
export const PROJECT_POST = "[PROJECT] GET_PROJECT";
export const PROJECT_POST_ERR = "[PROJECT] PROJECT_POST_ERR";
export const PROJECT_GET_ERR = "[PROJECT] PROJECT_GET_ERR";
